namespace Exception {

    export enum Errors {

        //! ALREADY_EXISTS_START

            EMPLOYEE_PHONE_NUMBER_ALREADY_EXISTS = 'EMPLOYEE_PHONE_NUMBER_ALREADY_EXISTS',
            ADDRESS_DISTRICT_ALREADY_EXISTS = 'ADDRESS_DISTRICT_ALREADY_EXISTS',
            ADDRESS_STREET_ALREADY_EXISTS = 'ADDRESS_STREET_ALREADY_EXISTS',
            WORKSHIFT_TEXT_ALREADY_EXISTS = 'WORKSHIFT_TEXT_ALREADY_EXISTS',
            ADDRESS_REGION_ALREADY_EXIST = 'ADDRESS_REGION_ALREADY_EXIST',
            DEPARTMENT_ALREADY_EXISTS = 'DEPARTMENT_ALREADY_EXISTS',
            EMPLOYEE_ALREADY_RESTORED = 'EMPLOYEE_ALREADY_RESTORED',
            EMPLOYEE_ALREADY_DELETED = 'EMPLOYEE_ALREADY_DELETED',
            WORKSHIFT_ALREADY_EXISTS = 'WORKSHIFT_ALREADY_EXISTS',
            EMPLOYEE_ALREADY_EXISTS = 'EMPLOYEE_ALREADY_EXISTS',
            ROLE_ALREADY_EXISTS = 'ROLE_ALREADY_EXISTS',

        //! ALREADY_EXISTS_END


        //! NOT_FOUND_START

            ADDRESS_DISTRICT_NOT_FOUND = 'ADDRESS_DISTRICT_NOT_FOUND',
            ADDRESS_REGION_NOT_FOUND = 'ADDRESS_REGION_NOT_FOUND',
            ADDRESS_STREET_NOT_FOUND = 'ADDRESS_STREET_NOT_FOUND',
            EMPLOYEE_IMG_NOT_FOUND = 'EMPLOYEE_IMG_NOT_FOUND',
            COMPANY_IMG_NOT_FOUND = 'COMPANY_IMG_NOT_FOUND',
            BRANCH_IMG_NOT_FOUND = 'BRANCH_IMG_NOT_FOUND',
            DEPARTMENT_NOT_FOUND = 'DEPARTMENT_NOT_FOUND',
            WORKSHIFT_NOT_FOUND = 'WORKSHIFT_NOT_FOUND',
            DISTRICT_NOT_FOUND = 'DISTRICT_NOT_FOUND',
            EMPLOYEE_NOT_FOUND = 'EMPLOYEE_NOT_FOUND',
            ADDRESS_NOT_FOUND = 'ADDRESS_NOT_FOUND',
            COMPANY_NOT_FOUND = 'COMPANY_NOT_FOUND',
            DEVICE_NOT_FOUND = 'DEVICE_NOT_FOUND',
            BRANCH_NOT_FOUND = 'BRANCH_NOT_FOUND',
            REGION_NOT_FOUND = 'REGION_NOT_FOUND',
            STREET_NOT_FOUND = 'STREET_NOT_FOUND',
            ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
            SMS_NOT_FOUND = 'SMS_NOT_FOUND',

        //! NOT_FOUND_END
        
        
        //! VALIDATION_ERROR_START
        
            EMPLOYEE_IS_NOT_ADMIN = 'EMPLOYEE_IS_NOT_ADMIN',
            VALIDATION_ERROR = 'VALIDATION_ERROR',
            UPLOAD_ERROR = 'UPLOAD_ERROR',

        //! VALIDATION_ERROR_END


        //! AUTHORIZATION_ERROR_START
        
            AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR',
            INVALID_TOKEN = 'INVALID_TOKEN',
            TOKEN_EXPIRED = 'TOKEN_EXPIRED',
            TOKEN_REVOKED = 'TOKEN_REVOKED',
            UNAUTHORIZED = 'UNAUTHORIZED',
            BAD_TOKEN = "BAD_TOKEN",

        //! AUTHORIZATION_ERROR_END

        
        //! SERVER_CONFIG_START

            ERROR_ON_GETTING_FILE_UPLOAD_ACCESS = 'ERROR_ON_GETTING_FILE_UPLOAD_ACCESS',
            ERROR_ON_GETTING_IMAGE = 'ERROR_ON_GETTING_IMAGE',
            INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
            HEADERS_REQUIRED = 'HEADERS_REQUIRED',
            BAD_JSON_FORMAT = 'BAD_JSON_FORMAT',
            UTC_REQUIRED = 'UTC_REQUIRED',

        //! SERVER_CONFIG_END


        //! BAD_VALUES_START
        
            ADDRESS_DISTRICT_HAS_STREETS = 'ADDRESS_DISTRICT_HAS_STREETS',
            ADDRESS_REGION_HAS_DISTRICTS = 'ADDRESS_REGION_HAS_DISTRICTS',
            DISTRICT_NOT_BELONG_REGION = 'DISTRICT_NOT_BELONG_REGION',
            ADDRESS_STREET_HAS_ADDRESS = 'ADDRESS_STREET_HAS_ADDRESS',
            STREET_NOT_BELONG_DISTRICT = 'STREET_NOT_BELONG_DISTRICT',
            DEPARTMENT_HAS_EMPLOYEES = 'DEPARTMENT_HAS_EMPLOYEES',
            WORKSHIFT_HAS_EMPLOYEES = 'WORKSHIFT_HAS_EMPLOYEES',
            PHONE_NUMBERS_ARE_SAME = 'PHONE_NUMBERS_ARE_SAME',
            COMPANY_IMG_NOT_EXISTS = 'COMPANY_IMG_NOT_EXISTS',
            BRANCH_IMG_NOT_EXIST = 'BRANCH_IMG_NOT_EXIST',
            ROLE_HAS_EMPLOYEES = 'ROLE_HAS_EMPLOYEES',
            FORBIDDEN_ERROR = 'FORBIDDEN_ERROR',
            ADDRESS_ERROR = 'ADDRESS_ERROR',
            BAD_REQUEST = 'BAD_REQUEST',
        
        //! BAD_VALUES_END
        
    };
    
    export class HttpException {
        status: number;
        message: string;
        error: Errors;
        
        constructor(status: number, message: string, error: Errors) {
            this.status = status;
            this.message = message || '';
            this.error = error;
        }
    }

}

export default Exception